// ============================================================================
// Landing page i18n content (TR / EN / DE). Extracted verbatim from the
// original page.tsx so the rebuilt landing keeps identical copy.
// ============================================================================

export const labels = {
    tr: {
      hero: {
        badge: '📊 İstatistiksel Tahmin Motoru',
        title: 'Veriyle Eğitilmiş',
        titleHighlight: 'Futbol Tahmin Motoru',
        subtitle: 'Binlerce gerçek maçla eğitilmiş Dixon-Coles istatistik modeli; 1X2, Üst/Alt 2.5 ve Karşılıklı Gol için kalibre olasılıklar üretir. Her gün otomatik güncellenir.',
        cta: 'Ücretsiz Başla',
        ctaSecondary: 'Nasıl Çalışır?',
        trustedBy: 'Profesyonel futbol analiz platformu',
        line1: 'Sayılar anlatır',
        line2: 'güzel oyunu',
        paraLeft: 'Her maç, sayıların içinde bir hikâye saklar — doksan dakikanın altında katman katman gol beklentisi, form eğrileri ve olasılıklar.',
        paraRight: 'Tahmin motorumuz oyunun yüzeyini aralar; xG, ELO ve piyasa oranlarının bir sonraki maçı nasıl şekillendirdiğini gösterir.',
        ctaButton: 'Analize Başla',
      },
      engineHow: {
        badge: '⚙️ Nasıl Çalışır',
        title: 'Tahminler Nasıl Üretiliyor?',
        subtitle: 'Sezgi değil, istatistik. Şeffaf ve tekrar üretilebilir bir model.',
        steps: [
          { icon: '📥', title: 'Gerçek Veri', desc: 'Binlerce bitmiş maç sonucu sürekli toplanır.' },
          { icon: '🧮', title: 'Dixon-Coles', desc: 'Zaman ağırlıklı Poisson + Dixon-Coles ile takım hücum/savunma güçleri öğrenilir.' },
          { icon: '🎯', title: 'Kalibre Olasılık', desc: '1X2, Üst/Alt 2.5 ve KG için kalibre olasılıklar hesaplanır.' },
          { icon: '🔄', title: 'Günlük Otomatik', desc: 'Her gün yarının maçları otomatik tahmin edilip yayınlanır.' },
        ],
      },
      livePredictions: {
        badge: '🎯 CANLI',
        title: 'Canlı İstatistik Tahminleri',
        subtitle: 'Gerçek maç verisiyle eğitilmiş Dixon-Coles motoru — her gün otomatik güncellenen kalibre olasılıklar.',
        cta: 'Tüm tahminleri gör',
        lockCta: 'Giriş yap · 7 gün ücretsiz dene',
      },
      stats: [
        { value: 'Dixon-Coles', label: 'İstatistik Motoru' },
        { value: 'Günlük', label: 'Otomatik Tahminler' },
        { value: '1X2 · Üst · KG', label: 'Tahmin Pazarları' },
        { value: 'TR · EN · DE', label: 'Dil Desteği' },
      ],
      features: {
        title: 'Neden Football Analytics Pro?',
        subtitle: 'Rakiplerinizden bir adım önde olmanızı sağlayan özellikler',
        items: [
          { icon: '📈', title: 'Çoklu Pazar', desc: '1X2, Üst/Alt 2.5 ve Karşılıklı Gol olasılıkları' },
          { icon: '🎯', title: 'Kalibre Olasılıklar', desc: 'Dixon-Coles ile kalibre edilmiş olasılıklar' },
          { icon: '🔄', title: 'Günlük Güncelleme', desc: 'Her gün otomatik üretilen yeni tahminler' },
          { icon: '🧮', title: 'İstatistiksel Model', desc: 'Sezgi değil; zaman ağırlıklı Poisson + Dixon-Coles' },
          { icon: '🌍', title: 'Çoklu Lig', desc: 'Birçok ligde günlük kapsama' },
          { icon: '🔒', title: 'Güvenli & Gizli', desc: 'Verileriniz şifrelenerek korunur' },
        ],
      },
      tipsterLeague: {
        badge: '🏆 YENİ',
        title: 'Tipster League',
        subtitle: 'Kupon oluştur, yarış, kazan!',
        description: 'Kendi kuponlarını oluştur, diğer kullanıcılarla yarış ve liderlik tablosunda yüksel. En iyi tipster\'lar ödül kazanır!',
        features: [
          { icon: '📝', title: 'Kupon Oluştur', desc: 'AI destekli maçlardan kuponunu yap' },
          { icon: '⭐', title: 'Puan Kazan', desc: 'Doğru tahminler ile puan topla' },
          { icon: '🏅', title: 'Liderlik Tablosu', desc: 'Haftalık ve aylık sıralamalar' },
          { icon: '🎁', title: 'Ödül Kazan', desc: 'En iyiler premium üyelik kazanır' },
        ],
        howItWorks: [
          { step: '1', title: 'Üye Ol', desc: 'Ücretsiz hesap oluştur' },
          { step: '2', title: 'Analiz Al', desc: 'AI tahminlerini incele' },
          { step: '3', title: 'Kupon Yap', desc: 'Maçları seç, kuponunu oluştur' },
          { step: '4', title: 'Yarış', desc: 'Liderlik tablosunda yüksel' },
        ],
        multipliers: {
          title: 'Puan Çarpanları',
          items: [
            { type: 'Tekli', multiplier: '×10' },
            { type: '2\'li', multiplier: '×15' },
            { type: '3\'lü', multiplier: '×25' },
            { type: '4+', multiplier: '×50' },
          ],
        },
        joinCta: '🏆 Hemen Katıl',
        aiPerfCta: '🧠 AI Performans',
      },
      proHighlight: {
        badge: '🚀 PRO ÜYELİK AVANTAJLARI',
        title: 'Sınırsız Erişim, Maksimum Kazanç',
        subtitle: 'Pro üyelikle tüm tahminlere ve derin analize sınırsız erişim',
        cta: 'Hemen Pro\'ya Geç',
        systems: [
          {
            icon: '📊',
            name: 'İstatistik Motoru',
            desc: 'Dixon-Coles ile kalibre edilmiş 1X2, Üst/Alt 2.5 ve KG olasılıkları — her gün otomatik güncellenir.',
            highlight: 'Dixon-Coles',
          },
          {
            icon: '🔓',
            name: 'Sınırsız Tahmin',
            desc: 'Tüm günlük motor tahminlerine ve lig bazlı görünümlere sınırsız erişim.',
            highlight: 'Sınırsız',
          },
          {
            icon: '🧠',
            name: 'Derin Maç Analizi',
            desc: 'Seçtiğin maç için detaylı, yapay zeka destekli analiz ve gerekçe.',
            highlight: 'AI Analiz',
          },
        ],
        bottomText: '💡 Üye olmadan tahminler kilitli. Pro ile tüm tahminlere ve derin analize sınırsız erişin!',
      },
      pricing: {
        title: 'Basit & Şeffaf Fiyatlandırma',
        subtitle: 'Sizin için en uygun planı seçin',
        free: {
          name: 'Ücretsiz',
          price: '$0',
          period: '/ay',
          features: ['Günlük 3 maç analizi', 'Temel istatistikler', 'Tipster League katılım', 'Email destek'],
          cta: 'Başla',
        },
        pro: {
          badge: 'EN POPÜLER',
          name: 'Pro',
          price: '$19.99',
          period: '/ay',
          features: ['Sınırsız motor tahminleri', 'Tüm pazarlar (1X2 · Üst/Alt · KG)', 'Derin AI maç analizi', 'Kupon oluşturma', 'Lig bazlı görünümler', 'Öncelikli destek'],
          cta: 'Pro\'ya Geç',
          trial: '🎁 7 Gün Ücretsiz Deneme',
          trialDesc: 'Kredi kartı bilgilerinizi girdikten sonra 7 gün ücretsiz deneyin. İstediğiniz zaman anında iptal edin!',
          cancelAnytime: '✓ İstediğiniz zaman iptal',
        },
      },
      matchIntel: {
        badge: '🧠 YENİ · Match Intelligence',
        title: 'Her maç için akıllı önizleme',
        subtitle: 'İstatistiksel olasılıklar + yapay zekâ haber özeti + 3 dilde maç anlatısı — hepsi tek kartta.',
        bullets: [
          { icon: '📊', title: 'Gerçek olasılıklar', desc: 'Tahminler istatistik modelinden gelir — yapay zekâ skor uydurmaz.' },
          { icon: '📰', title: 'Haber & sakatlık özeti', desc: 'Maç öncesi önemli gelişmeler nötr ve sade biçimde derlenir.' },
          { icon: '🌍', title: '3 dil (TR · EN · DE)', desc: 'Her önizleme Türkçe, İngilizce ve Almanca hazır.' },
          { icon: '🌙', title: 'Her gece güncel', desc: 'Yaklaşan maçlar otomatik analiz edilir, sabaha hazır olur.' },
        ],
        sampleLabel: 'Örnek',
        sampleLeague: 'FIFA Dünya Kupası',
        sampleHome: 'Fransa', sampleAway: 'Belçika',
        probHome: 'Fransa %46', probDraw: 'Beraberlik %27', probAway: 'Belçika %27',
        over: 'Üst 2.5', btts: 'KG Var', previewLabel: 'Önizleme',
        samplePreview: 'Fransa istatistiksel olarak hafif favori (%46). Beklenen goller yakın; her iki takımın da gol atma olasılığı yüksek. Sakatlık tablosu dengeli.',
        cta: 'Ücretsiz Dene',
      },
      testimonials: {
        title: 'Kullanıcılarımız Ne Diyor?',
        items: [
          { text: 'Kalibre olasılıklar çok işime yarıyor; tahminlerin arkasındaki mantığı görmek güven veriyor.', author: 'Ahmet K.', role: 'Pro Üye' },
          { text: 'Her sabah güncel tahminler hazır oluyor. İstatistiksel yaklaşım sezgiye göre çok daha tutarlı.', author: 'Mehmet Y.', role: 'Futbol Analisti' },
          { text: 'Tipster League sayesinde ayın en iyi tahminleri yapanı oldum!', author: 'Can S.', role: 'Tipster League Şampiyonu' },
        ],
      },
      cta: {
        title: 'İstatistik Motorunu Deneyin',
        subtitle: 'Ücretsiz hesap oluşturun, kalibre tahminlere erişin!',
        button: 'Ücretsiz Hesap Oluştur',
      },
      footer: {
        product: 'Ürün',
        features: 'Özellikler',
        pricing: 'Fiyatlandırma',
        demo: 'Demo',
        tipsterLeague: 'Tipster League',
        company: 'Şirket',
        about: 'Hakkımızda',
        blog: 'Blog',
        careers: 'Kariyer',
        legal: 'Yasal',
        privacy: 'Gizlilik',
        terms: 'Kullanım Şartları',
        copyright: '© 2026 Football Analytics Pro. Tüm hakları saklıdır.',
        poweredBy: 'Dixon-Coles istatistik motoru',
        developedBy: 'Swiss Digital tarafından geliştirildi',
      },
    },
    en: {
      hero: {
        badge: '📊 Statistical Prediction Engine',
        title: 'A Football Prediction Engine',
        titleHighlight: 'Trained on Real Data',
        subtitle: 'A Dixon-Coles statistical model trained on thousands of real matches; it produces calibrated probabilities for 1X2, Over/Under 2.5 and Both Teams To Score. Updated automatically every day.',
        cta: 'Start Free',
        ctaSecondary: 'How It Works?',
        trustedBy: 'Professional football analytics platform',
        line1: 'Numbers tell',
        line2: 'the beautiful game',
        paraLeft: 'Every match hides a story in the numbers — expected goals, form curves and probabilities layered beneath ninety minutes of play.',
        paraRight: 'Our prediction engine peels back the surface of the game, revealing how xG, ELO and market odds shape what happens next.',
        ctaButton: 'Start Analyzing',
      },
      engineHow: {
        badge: '⚙️ How It Works',
        title: 'How Predictions Are Generated',
        subtitle: 'Not intuition — statistics. A transparent, reproducible model.',
        steps: [
          { icon: '📥', title: 'Real Data', desc: 'Thousands of finished match results are continuously collected.' },
          { icon: '🧮', title: 'Dixon-Coles', desc: 'Time-weighted Poisson + Dixon-Coles learns each team\'s attack/defense strength.' },
          { icon: '🎯', title: 'Calibrated Odds', desc: 'Calibrated probabilities are computed for 1X2, Over/Under 2.5 and BTTS.' },
          { icon: '🔄', title: 'Daily Auto', desc: 'Tomorrow\'s matches are predicted and published automatically every day.' },
        ],
      },
      livePredictions: {
        badge: '🎯 LIVE',
        title: 'Live Statistical Predictions',
        subtitle: 'Dixon-Coles engine trained on real match data — calibrated probabilities, updated automatically every day.',
        cta: 'See all predictions',
        lockCta: 'Sign in · 7-day free trial',
      },
      stats: [
        { value: 'Dixon-Coles', label: 'Statistical Engine' },
        { value: 'Daily', label: 'Auto Predictions' },
        { value: '1X2 · O/U · BTTS', label: 'Prediction Markets' },
        { value: 'TR · EN · DE', label: 'Languages' },
      ],
      features: {
        title: 'Why Football Analytics Pro?',
        subtitle: 'Features that keep you ahead of the competition',
        items: [
          { icon: '📈', title: 'Multiple Markets', desc: '1X2, Over/Under 2.5 and Both Teams To Score probabilities' },
          { icon: '🎯', title: 'Calibrated Probabilities', desc: 'Calibrated probabilities via Dixon-Coles' },
          { icon: '🔄', title: 'Daily Updates', desc: 'Fresh predictions generated automatically every day' },
          { icon: '🧮', title: 'Statistical Model', desc: 'Not intuition — time-weighted Poisson + Dixon-Coles' },
          { icon: '🌍', title: 'Multiple Leagues', desc: 'Daily coverage across many leagues' },
          { icon: '🔒', title: 'Secure & Private', desc: 'Your data is encrypted and protected' },
        ],
      },
      tipsterLeague: {
        badge: '🏆 NEW',
        title: 'Tipster League',
        subtitle: 'Create coupons, compete, win!',
        description: 'Create your own coupons, compete with other users and climb the leaderboard. Top tipsters win prizes!',
        features: [
          { icon: '📝', title: 'Create Coupons', desc: 'Make your coupon from AI-powered matches' },
          { icon: '⭐', title: 'Earn Points', desc: 'Collect points with correct predictions' },
          { icon: '🏅', title: 'Leaderboard', desc: 'Weekly and monthly rankings' },
          { icon: '🎁', title: 'Win Prizes', desc: 'Top performers get premium membership' },
        ],
        howItWorks: [
          { step: '1', title: 'Sign Up', desc: 'Create free account' },
          { step: '2', title: 'Get Analysis', desc: 'Review AI predictions' },
          { step: '3', title: 'Make Coupon', desc: 'Select matches, create your coupon' },
          { step: '4', title: 'Compete', desc: 'Climb the leaderboard' },
        ],
        multipliers: {
          title: 'Point Multipliers',
          items: [
            { type: 'Single', multiplier: '×10' },
            { type: 'Double', multiplier: '×15' },
            { type: 'Triple', multiplier: '×25' },
            { type: '4+', multiplier: '×50' },
          ],
        },
        joinCta: '🏆 Join Now',
        aiPerfCta: '🧠 AI Performance',
      },
      proHighlight: {
        badge: '🚀 PRO MEMBERSHIP BENEFITS',
        title: 'Unlimited Access, Maximum Profit',
        subtitle: 'Get unlimited access to all predictions and deep analysis with Pro',
        cta: 'Go Pro Now',
        systems: [
          {
            icon: '📊',
            name: 'Statistical Engine',
            desc: 'Dixon-Coles calibrated probabilities for 1X2, Over/Under 2.5 and BTTS — updated automatically every day.',
            highlight: 'Dixon-Coles',
          },
          {
            icon: '🔓',
            name: 'Unlimited Predictions',
            desc: 'Unlimited access to all daily engine predictions and league-by-league views.',
            highlight: 'Unlimited',
          },
          {
            icon: '🧠',
            name: 'Deep Match Analysis',
            desc: 'Detailed, AI-powered analysis and rationale for the match you pick.',
            highlight: 'AI Analysis',
          },
        ],
        bottomText: '💡 Predictions are locked without an account. Go Pro for unlimited access to all predictions and deep analysis!',
      },
      pricing: {
        title: 'Simple & Transparent Pricing',
        subtitle: 'Choose the plan that fits you best',
        free: {
          name: 'Free',
          price: '$0',
          period: '/month',
          features: ['3 match analyses daily', 'Basic statistics', 'Tipster League access', 'Email support'],
          cta: 'Get Started',
        },
        pro: {
          badge: 'MOST POPULAR',
          name: 'Pro',
          price: '$19.99',
          period: '/month',
          features: ['Unlimited engine predictions', 'All markets (1X2 · O/U · BTTS)', 'Deep AI match analysis', 'Coupon creation', 'League-by-league views', 'Priority support'],
          cta: 'Go Pro',
          trial: '🎁 7-Day Free Trial',
          trialDesc: 'Try free for 7 days after entering your card details. Cancel instantly anytime!',
          cancelAnytime: '✓ Cancel anytime',
        },
      },
      matchIntel: {
        badge: '🧠 NEW · Match Intelligence',
        title: 'A smart preview for every match',
        subtitle: 'Statistical probabilities + AI news digest + match narrative in 3 languages — all in one card.',
        bullets: [
          { icon: '📊', title: 'Real probabilities', desc: 'Predictions come from a statistical model — the AI never invents a score.' },
          { icon: '📰', title: 'News & injury digest', desc: 'Key pre-match developments, summarised neutrally and clearly.' },
          { icon: '🌍', title: '3 languages (TR · EN · DE)', desc: 'Every preview ready in Turkish, English and German.' },
          { icon: '🌙', title: 'Updated nightly', desc: 'Upcoming matches are analysed automatically, ready by morning.' },
        ],
        sampleLabel: 'Example',
        sampleLeague: 'FIFA World Cup',
        sampleHome: 'France', sampleAway: 'Belgium',
        probHome: 'France 46%', probDraw: 'Draw 27%', probAway: 'Belgium 27%',
        over: 'Over 2.5', btts: 'BTTS', previewLabel: 'Preview',
        samplePreview: 'France are slight statistical favourites (46%). Expected goals are close; both teams are likely to score. The injury picture is balanced.',
        cta: 'Try it free',
      },
      testimonials: {
        title: 'What Our Users Say',
        items: [
          { text: 'The calibrated probabilities are genuinely useful; seeing the logic behind each prediction builds trust.', author: 'John D.', role: 'Pro Member' },
          { text: 'Fresh predictions are ready every morning. The statistical approach is far more consistent than gut feeling.', author: 'Mike R.', role: 'Football Analyst' },
          { text: 'Thanks to Tipster League I became the top predictor of the month!', author: 'Chris S.', role: 'Tipster League Champion' },
        ],
      },
      cta: {
        title: 'Try the Statistical Engine',
        subtitle: 'Create a free account and access calibrated predictions!',
        button: 'Create Free Account',
      },
      footer: {
        product: 'Product',
        features: 'Features',
        pricing: 'Pricing',
        demo: 'Demo',
        tipsterLeague: 'Tipster League',
        company: 'Company',
        about: 'About',
        blog: 'Blog',
        careers: 'Careers',
        legal: 'Legal',
        privacy: 'Privacy',
        terms: 'Terms',
        copyright: '© 2026 Football Analytics Pro. All rights reserved.',
        poweredBy: 'Powered by the Dixon-Coles statistical engine',
        developedBy: 'Developed by Swiss Digital',
      },
    },
  };

export const labelsDE = {
    hero: {
      badge: '📊 Statistische Vorhersage-Engine',
      title: 'Eine Fußball-Vorhersage-Engine',
      titleHighlight: 'mit echten Daten trainiert',
      subtitle: 'Ein Dixon-Coles-Statistikmodell, trainiert mit Tausenden echten Spielen; es liefert kalibrierte Wahrscheinlichkeiten für 1X2, Über/Unter 2.5 und Beide Teams treffen. Täglich automatisch aktualisiert.',
      cta: 'Kostenlos starten',
      ctaSecondary: 'Wie funktioniert es?',
      trustedBy: 'Professionelle Fußball-Analyse-Plattform',
      line1: 'Zahlen erzählen',
      line2: 'das schöne Spiel',
      paraLeft: 'Jedes Spiel verbirgt eine Geschichte in den Zahlen — Expected Goals, Formkurven und Wahrscheinlichkeiten, geschichtet unter neunzig Minuten Fußball.',
      paraRight: 'Unsere Prediction-Engine legt die Oberfläche des Spiels frei und zeigt, wie xG, ELO und Marktquoten das nächste Spiel formen.',
      ctaButton: 'Jetzt analysieren',
    },
    engineHow: {
      badge: '⚙️ Wie es funktioniert',
      title: 'Wie Vorhersagen entstehen',
      subtitle: 'Keine Intuition — Statistik. Ein transparentes, reproduzierbares Modell.',
      steps: [
        { icon: '📥', title: 'Echte Daten', desc: 'Tausende abgeschlossene Spielergebnisse werden laufend gesammelt.' },
        { icon: '🧮', title: 'Dixon-Coles', desc: 'Zeitgewichtetes Poisson + Dixon-Coles lernt die Angriffs-/Abwehrstärke jedes Teams.' },
        { icon: '🎯', title: 'Kalibrierte Quote', desc: 'Kalibrierte Wahrscheinlichkeiten für 1X2, Über/Unter 2.5 und BTTS werden berechnet.' },
        { icon: '🔄', title: 'Täglich automatisch', desc: 'Die Spiele von morgen werden täglich automatisch vorhergesagt und veröffentlicht.' },
      ],
    },
    livePredictions: {
      badge: '🎯 LIVE',
      title: 'Live-Statistik-Vorhersagen',
      subtitle: 'Dixon-Coles-Engine mit echten Spieldaten trainiert — kalibrierte Wahrscheinlichkeiten, täglich automatisch aktualisiert.',
      cta: 'Alle Vorhersagen ansehen',
      lockCta: 'Anmelden · 7 Tage kostenlos',
    },
    stats: [
      { value: 'Dixon-Coles', label: 'Statistik-Engine' },
      { value: 'Täglich', label: 'Auto-Vorhersagen' },
      { value: '1X2 · Ü/U · BTTS', label: 'Wettmärkte' },
      { value: 'TR · EN · DE', label: 'Sprachen' },
    ],
    features: {
      title: 'Warum Football Analytics Pro?',
      subtitle: 'Funktionen, die Sie der Konkurrenz einen Schritt voraus halten',
      items: [
        { icon: '📈', title: 'Mehrere Märkte', desc: '1X2, Über/Unter 2.5 und Beide Teams treffen — Wahrscheinlichkeiten' },
        { icon: '🎯', title: 'Kalibrierte Wahrscheinlichkeiten', desc: 'Kalibrierte Wahrscheinlichkeiten via Dixon-Coles' },
        { icon: '🔄', title: 'Tägliche Updates', desc: 'Täglich automatisch erzeugte neue Vorhersagen' },
        { icon: '🧮', title: 'Statistisches Modell', desc: 'Keine Intuition — zeitgewichtetes Poisson + Dixon-Coles' },
        { icon: '🌍', title: 'Mehrere Ligen', desc: 'Tägliche Abdeckung über viele Ligen' },
        { icon: '🔒', title: 'Sicher & Privat', desc: 'Ihre Daten werden verschlüsselt geschützt' },
      ],
    },
    tipsterLeague: {
      badge: '🏆 NEU',
      title: 'Tipster League',
      subtitle: 'Erstelle Wettscheine, konkurriere, gewinne!',
      description: 'Erstelle eigene Wettscheine, konkurriere mit anderen Nutzern und steige in der Rangliste auf. Top-Tipster gewinnen Preise!',
      features: [
        { icon: '📝', title: 'Wettschein erstellen', desc: 'Erstelle Wettscheine mit KI-gestützten Spielen' },
        { icon: '⭐', title: 'Punkte sammeln', desc: 'Sammle Punkte mit richtigen Vorhersagen' },
        { icon: '🏅', title: 'Rangliste', desc: 'Wöchentliche und monatliche Rankings' },
        { icon: '🎁', title: 'Preise gewinnen', desc: 'Top-Performer erhalten Premium-Mitgliedschaft' },
      ],
      howItWorks: [
        { step: '1', title: 'Registrieren', desc: 'Kostenloses Konto erstellen' },
        { step: '2', title: 'Analyse erhalten', desc: 'KI-Vorhersagen prüfen' },
        { step: '3', title: 'Wettschein erstellen', desc: 'Spiele auswählen, Wettschein erstellen' },
        { step: '4', title: 'Konkurrieren', desc: 'In der Rangliste aufsteigen' },
      ],
      multipliers: {
        title: 'Punktemultiplikatoren',
        items: [
          { type: 'Einzel', multiplier: '×10' },
          { type: 'Doppel', multiplier: '×15' },
          { type: 'Dreifach', multiplier: '×25' },
          { type: '4+', multiplier: '×50' },
        ],
      },
      joinCta: '🏆 Jetzt mitmachen',
      aiPerfCta: '🧠 KI-Leistung',
    },
    proHighlight: {
      badge: '🚀 PRO-MITGLIEDSCHAFT VORTEILE',
      title: 'Unbegrenzter Zugang, maximaler Gewinn',
      subtitle: 'Mit Pro unbegrenzter Zugang zu allen Vorhersagen und der Tiefenanalyse',
      cta: 'Jetzt Pro werden',
      systems: [
        {
          icon: '📊',
          name: 'Statistik-Engine',
          desc: 'Dixon-Coles kalibrierte Wahrscheinlichkeiten für 1X2, Über/Unter 2.5 und BTTS — täglich automatisch aktualisiert.',
          highlight: 'Dixon-Coles',
        },
        {
          icon: '🔓',
          name: 'Unbegrenzte Vorhersagen',
          desc: 'Unbegrenzter Zugang zu allen täglichen Engine-Vorhersagen und Liga-Ansichten.',
          highlight: 'Unbegrenzt',
        },
        {
          icon: '🧠',
          name: 'Tiefen-Spielanalyse',
          desc: 'Detaillierte, KI-gestützte Analyse und Begründung für das gewählte Spiel.',
          highlight: 'KI-Analyse',
        },
      ],
      bottomText: '💡 Ohne Konto sind die Vorhersagen gesperrt. Mit Pro unbegrenzter Zugang zu allen Vorhersagen und der Tiefenanalyse!',
    },
    pricing: {
      title: 'Einfache & transparente Preise',
      subtitle: 'Wählen Sie den Plan, der am besten zu Ihnen passt',
      free: {
        name: 'Kostenlos',
        price: '€0',
        period: '/Monat',
        features: ['3 Spielanalysen täglich', 'Basis-Statistiken', 'Tipster League Zugang', 'E-Mail-Support'],
        cta: 'Loslegen',
      },
      pro: {
        badge: 'AM BELIEBTESTEN',
        name: 'Pro',
        price: '$19.99',
        period: '/Monat',
        features: ['Unbegrenzte Engine-Vorhersagen', 'Alle Märkte (1X2 · Ü/U · BTTS)', 'Tiefe KI-Spielanalyse', 'Wettschein-Erstellung', 'Liga-Ansichten', 'Prioritäts-Support'],
        cta: 'Pro werden',
        trial: '🎁 7 Tage kostenlos testen',
        trialDesc: 'Nach Eingabe Ihrer Kartendaten 7 Tage kostenlos testen. Jederzeit sofort kündigen!',
        cancelAnytime: '✓ Jederzeit kündbar',
      },
    },
    matchIntel: {
      badge: '🧠 NEU · Match Intelligence',
      title: 'Eine smarte Vorschau für jedes Spiel',
      subtitle: 'Statistische Wahrscheinlichkeiten + KI-Nachrichten + Spielvorschau in 3 Sprachen — alles in einer Karte.',
      bullets: [
        { icon: '📊', title: 'Echte Wahrscheinlichkeiten', desc: 'Prognosen stammen aus einem statistischen Modell — die KI erfindet kein Ergebnis.' },
        { icon: '📰', title: 'Nachrichten & Verletzungen', desc: 'Wichtige Entwicklungen vor dem Spiel, neutral und klar zusammengefasst.' },
        { icon: '🌍', title: '3 Sprachen (TR · EN · DE)', desc: 'Jede Vorschau auf Türkisch, Englisch und Deutsch bereit.' },
        { icon: '🌙', title: 'Jede Nacht aktuell', desc: 'Bevorstehende Spiele werden automatisch analysiert, bis zum Morgen bereit.' },
      ],
      sampleLabel: 'Beispiel',
      sampleLeague: 'FIFA-Weltmeisterschaft',
      sampleHome: 'Frankreich', sampleAway: 'Belgien',
      probHome: 'Frankreich 46%', probDraw: 'Unentschieden 27%', probAway: 'Belgien 27%',
      over: 'Über 2.5', btts: 'BTTS', previewLabel: 'Vorschau',
      samplePreview: 'Frankreich ist statistisch leicht favorisiert (46%). Die erwarteten Tore liegen nahe beieinander; beide Teams treffen wahrscheinlich. Die Verletzungslage ist ausgeglichen.',
      cta: 'Kostenlos testen',
    },
    testimonials: {
      title: 'Was unsere Nutzer sagen',
      items: [
        { text: 'Die kalibrierten Wahrscheinlichkeiten sind wirklich nützlich; die Logik hinter jeder Vorhersage zu sehen schafft Vertrauen.', author: 'Thomas M.', role: 'Pro-Mitglied' },
        { text: 'Jeden Morgen sind frische Vorhersagen bereit. Der statistische Ansatz ist viel konsistenter als das Bauchgefühl.', author: 'Stefan K.', role: 'Fußball-Analyst' },
        { text: 'Dank Tipster League wurde ich zum Top-Predictor des Monats!', author: 'Markus H.', role: 'Tipster League Champion' },
      ],
    },
    cta: {
      title: 'Testen Sie die Statistik-Engine',
      subtitle: 'Erstellen Sie ein kostenloses Konto und greifen Sie auf kalibrierte Vorhersagen zu!',
      button: 'Kostenloses Konto erstellen',
    },
    footer: {
      product: 'Produkt',
      features: 'Funktionen',
      pricing: 'Preise',
      demo: 'Demo',
      tipsterLeague: 'Tipster League',
      company: 'Unternehmen',
      about: 'Über uns',
      blog: 'Blog',
      careers: 'Karriere',
      legal: 'Rechtliches',
      privacy: 'Datenschutz',
      terms: 'AGB',
      copyright: '© 2026 Football Analytics Pro. Alle Rechte vorbehalten.',
      poweredBy: 'Angetrieben von der Dixon-Coles-Statistik-Engine',
      developedBy: 'Entwickelt von Swiss Digital',
    },
  };
