const LEAGUE_BUTTONS = [
  { key: 'premier_league', name: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 Premier League', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { key: 'championship', name: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 Championship', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { key: 'la_liga', name: '🇪🇸 La Liga', flag: '🇪🇸' },
  { key: 'serie_a', name: '🇮🇹 Serie A', flag: '🇮🇹' },
  { key: 'bundesliga', name: '🇩🇪 Bundesliga', flag: '🇩🇪' },
  { key: 'ligue_1', name: '🇫🇷 Ligue 1', flag: '🇫🇷' },
  { key: 'super_lig', name: '🇹🇷 Süper Lig', flag: '🇹🇷' },
  { key: 'eredivisie', name: '🇳🇱 Eredivisie', flag: '🇳🇱' },
  { key: 'liga_portugal', name: '🇵🇹 Liga Portugal', flag: '🇵🇹' },
  { key: 'pro_league', name: '🇧🇪 Pro League', flag: '🇧🇪' },
  { key: 'austria_bundesliga', name: '🇦🇹 Austria', flag: '🇦🇹' },
  { key: 'super_league_ch', name: '🇨🇭 Swiss League', flag: '🇨🇭' },
  { key: 'scottish_premiership', name: '🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { key: 'superliga_dk', name: '🇩🇰 Denmark', flag: '🇩🇰' },
  { key: 'eliteserien', name: '🇳🇴 Norway', flag: '🇳🇴' },
  { key: 'allsvenskan', name: '🇸🇪 Sweden', flag: '🇸🇪' },
  { key: 'ekstraklasa', name: '🇵🇱 Poland', flag: '🇵🇱' },
  { key: 'hnl', name: '🇭🇷 Croatia', flag: '🇭🇷' },
  { key: 'russia_premier', name: '🇷🇺 Russia', flag: '🇷🇺' },
  { key: 'ukraine_premier', name: '🇺🇦 Ukraine', flag: '🇺🇦' },
];
