const LEAGUES: Record<string, number> = {
  // England
  premier_league: 8,
  championship: 9,
  fa_cup: 24,
  carabao_cup: 27,
  // Spain
  la_liga: 564,
  la_liga_2: 567,
  copa_del_rey: 570,
  // Italy
  serie_a: 384,
  serie_b: 387,
  coppa_italia: 390,
  // Germany
  bundesliga: 82,
  // France
  ligue_1: 301,
  // Netherlands
  eredivisie: 72,
  // Portugal
  liga_portugal: 462,
  // Turkey
  super_lig: 600,
  // Belgium
  pro_league: 208,
  // Austria
  austria_bundesliga: 181,
  // Switzerland
  super_league_ch: 591,
  // Scotland
  scottish_premiership: 501,
  // Denmark
  superliga_dk: 271,
  // Norway
  eliteserien: 444,
  // Sweden
  allsvenskan: 573,
  // Poland
  ekstraklasa: 453,
  // Croatia
  hnl: 244,
  // Russia
  russia_premier: 486,
  // Ukraine
  ukraine_premier: 609,
  // Europe
  europa_league_playoffs: 1371,
};
